-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDe1x+Fz67Ee1jY0W52hI6cClzyhaiiRrSCDfYiUcEfKgCgYIKoZIzj0DAQehRANCAATpRGilbgATq3WDKezbLxtglukqZv/c9Seduj4SEfmIHAXr6Ceb0f1uX8XGjwkmfmQYEvxU+RA29fmdBcRW7zng
-----END PRIVATE KEY-----